-- Gradebook column groups: make the group a row.
--
-- Until now a "column group" was a string operation in the browser. `groupedColumns` in
-- manage/gradebook/gradebookTable.tsx split each slug on '-', took the first token (with a
-- special case for `assignment-<type>-*`), and started a new group whenever sort_order skipped
-- a number. Four other sites re-derived the same prefix, two of them without the special case.
-- Nothing in the database knew a group existed.
--
-- This migration creates the table, backfills every gradebook that already exists, and moves
-- column ordering to two levels: groups are ordered within a gradebook, columns within their
-- group. The old global gradebook_columns.sort_order is dropped rather than reinterpreted, so
-- that any reader we missed fails loudly instead of returning a plausible but wrong order.
--
-- The slug parsing below runs exactly once, here. After this commit nothing parses a slug to
-- decide what a column belongs to; the foreign key says.
--
-- Companion migration 20260920120100 rewrites the ordering routines that depend on this shape.

-- ---------------------------------------------------------------------------------------------
-- 0. Preconditions
-- ---------------------------------------------------------------------------------------------

-- 20260408120001 already drained NULL sort_order and taught the assignment trigger to compute
-- one. Re-run the drain defensively, then assert, because the backfill's equivalence proof is
-- only meaningful if every column has a position. Note the JS heuristic treats NULL as 0 (it
-- does `col.sort_order ?? 0`), which sorts NULLs FIRST, while every SQL path in this repo uses
-- NULLS LAST. Rather than reproduce that disagreement we make it unreachable.
DO $$
DECLARE
  v_nulls integer;
BEGIN
  UPDATE public.gradebook_columns gc
     SET sort_order = sub.new_order
    FROM (
      SELECT id,
             ROW_NUMBER() OVER (PARTITION BY gradebook_id ORDER BY id) - 1
               + COALESCE((SELECT MAX(sort_order) + 1
                             FROM public.gradebook_columns x
                            WHERE x.gradebook_id = gradebook_columns.gradebook_id
                              AND x.sort_order IS NOT NULL), 0) AS new_order
        FROM public.gradebook_columns
       WHERE sort_order IS NULL
    ) sub
   WHERE gc.id = sub.id;

  SELECT count(*) INTO v_nulls FROM public.gradebook_columns WHERE sort_order IS NULL;
  IF v_nulls > 0 THEN
    RAISE EXCEPTION 'gradebook_column_groups: % columns still have a NULL sort_order', v_nulls;
  END IF;
END $$;

-- ---------------------------------------------------------------------------------------------
-- 1. The table
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.gradebook_column_groups (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  class_id     bigint NOT NULL REFERENCES public.classes(id)    ON DELETE CASCADE,
  gradebook_id bigint NOT NULL REFERENCES public.gradebooks(id) ON DELETE CASCADE,
  name         text NOT NULL,
  slug         text NOT NULL,
  description  text,
  -- Position of this group among its gradebook's groups. Columns carry position_in_group;
  -- global display order is (group.sort_order, column.position_in_group, column.id).
  sort_order   integer NOT NULL,
  -- Share of the course total. NULL means "not weighted". Nothing computes from this until an
  -- instructor writes weighted_total() into a score_expression; see 20260920120100.
  weight       numeric,
  -- Exactly one per gradebook. Receives columns that no rule classifies, and is the target when
  -- a group is deleted. Cannot itself be deleted.
  is_default   boolean NOT NULL DEFAULT false,
  -- The legacy heuristic's baseGroupName. New columns whose slug derives this base are routed
  -- here automatically. NULL opts the group out of auto-routing, so an instructor who hand-curates
  -- a group keeps it hand-curated.
  auto_assign_slug_base text,
  CONSTRAINT gradebook_column_groups_slug_key
    UNIQUE (gradebook_id, slug),
  -- Referenced by the composite FK on gradebook_columns below. This is what makes it impossible
  -- to file a column under another gradebook's group.
  CONSTRAINT gradebook_column_groups_id_gradebook_key
    UNIQUE (id, gradebook_id),
  -- Deferrable: reordering groups swaps positions, which collides transiently.
  CONSTRAINT gradebook_column_groups_order_key
    UNIQUE (gradebook_id, sort_order) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT gradebook_column_groups_weight_chk
    CHECK (weight IS NULL OR weight >= 0)
);

COMMENT ON TABLE public.gradebook_column_groups IS
  'A gradebook column group. Replaces the slug-prefix heuristic that used to compute groups in the browser on every render.';
COMMENT ON COLUMN public.gradebook_column_groups.sort_order IS
  'Position among this gradebook''s groups. Columns are ordered within a group by gradebook_columns.position_in_group.';
COMMENT ON COLUMN public.gradebook_column_groups.auto_assign_slug_base IS
  'Legacy slug base that routes new columns here. NULL means the group does not auto-receive columns.';
COMMENT ON COLUMN public.gradebook_column_groups.weight IS
  'Share of the course total, read by the weighted_total() expression function. NULL means unweighted.';

CREATE UNIQUE INDEX IF NOT EXISTS gradebook_column_groups_one_default
  ON public.gradebook_column_groups (gradebook_id) WHERE is_default;
CREATE INDEX IF NOT EXISTS gradebook_column_groups_auto_assign_idx
  ON public.gradebook_column_groups (gradebook_id, auto_assign_slug_base)
  WHERE auto_assign_slug_base IS NOT NULL;
CREATE INDEX IF NOT EXISTS gradebook_column_groups_class_id_idx
  ON public.gradebook_column_groups (class_id);

-- ---------------------------------------------------------------------------------------------
-- 2. RLS
-- ---------------------------------------------------------------------------------------------
--
-- class_id is denormalized here for exactly one reason: both helpers below resolve to a
-- primary-key lookup on public.user_privileges (user_id, class_id), so a policy check is a single
-- index probe with no join back to gradebook_columns or gradebooks. That is the same shape the
-- hot gradebook tables already use.
--
-- Two deliberate differences from the policies next door on gradebook_columns. That table's
-- "instructors CRUD" policy has no WITH CHECK, which lets an instructor write a row naming a
-- class they do not teach; these policies have one. And these are scoped TO authenticated with
-- nothing granted to anon, following 20260825140000_audit_findings_2026_08.sql rather than the
-- 2025-era blanket grants.
--
-- Groups carry no scores, so class membership is the right bar for SELECT. A group whose columns
-- are all hidden from a student renders no header, because the client emits a header only for
-- groups that have visible members.

ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE public.gradebook_column_groups TO authenticated;
GRANT ALL    ON TABLE public.gradebook_column_groups TO service_role;

DROP POLICY IF EXISTS "everyone in class can view column groups" ON public.gradebook_column_groups;
CREATE POLICY "everyone in class can view column groups"
  ON public.gradebook_column_groups
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (public.authorizeforclass(class_id));

DROP POLICY IF EXISTS "instructors manage column groups" ON public.gradebook_column_groups;
CREATE POLICY "instructors manage column groups"
  ON public.gradebook_column_groups
  AS PERMISSIVE FOR ALL TO authenticated
  USING      (public.authorizeforclassinstructor(class_id))
  WITH CHECK (public.authorizeforclassinstructor(class_id));

-- ---------------------------------------------------------------------------------------------
-- 3. Triggers on the new table
-- ---------------------------------------------------------------------------------------------

DROP TRIGGER IF EXISTS set_updated_at_on_gradebook_column_groups ON public.gradebook_column_groups;
CREATE TRIGGER set_updated_at_on_gradebook_column_groups
  BEFORE UPDATE ON public.gradebook_column_groups
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Realtime publication is dead as of 20251009163916_disable-realtime.sql; the live path is
-- safe_broadcast, which no-ops when nobody holds a lease. Modelled on
-- broadcast_gradebook_columns_change(). Groups are low-churn, so row-level is fine here; the
-- per-student fan-out that forced gradebook_column_students to statement-level triggers is not a
-- concern at this write volume.
CREATE OR REPLACE FUNCTION public.broadcast_gradebook_column_groups_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    target_class_id BIGINT;
    staff_payload JSONB;
    user_payload JSONB;
    affected_profile_ids UUID[];
    profile_id UUID;
BEGIN
    IF TG_OP = 'INSERT' THEN
        target_class_id := NEW.class_id;
    ELSIF TG_OP = 'UPDATE' THEN
        target_class_id := COALESCE(NEW.class_id, OLD.class_id);
    ELSE
        target_class_id := OLD.class_id;
    END IF;

    IF target_class_id IS NULL THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
    END IF;

    staff_payload := jsonb_build_object(
        'type', 'table_change',
        'operation', TG_OP,
        'table', TG_TABLE_NAME,
        'row_id', CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
        'data',   CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END,
        'class_id', target_class_id,
        'target_audience', 'staff',
        'timestamp', NOW()
    );

    PERFORM public.safe_broadcast(
        staff_payload, 'broadcast', 'class:' || target_class_id || ':staff', true);

    SELECT ARRAY(
        SELECT ur.private_profile_id
          FROM public.user_roles ur
         WHERE ur.class_id = target_class_id AND ur.role = 'student'
    ) INTO affected_profile_ids;

    user_payload := staff_payload || jsonb_build_object('target_audience', 'user');

    FOREACH profile_id IN ARRAY affected_profile_ids
    LOOP
        PERFORM public.safe_broadcast(
            user_payload, 'broadcast',
            'class:' || target_class_id || ':user:' || profile_id, true);
    END LOOP;

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$;

DROP TRIGGER IF EXISTS broadcast_gradebook_column_groups_unified ON public.gradebook_column_groups;
CREATE TRIGGER broadcast_gradebook_column_groups_unified
  AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
  FOR EACH ROW EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();

-- Audit, matching the statement-level shape from 20251228143943_partitioned_audit_system.sql.
CREATE TRIGGER audit_gradebook_column_groups_insert
  AFTER INSERT ON public.gradebook_column_groups
  REFERENCING NEW TABLE AS NEW_TABLE
  FOR EACH STATEMENT EXECUTE FUNCTION public.audit_statement_trigger();
CREATE TRIGGER audit_gradebook_column_groups_update
  AFTER UPDATE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS OLD_TABLE NEW TABLE AS NEW_TABLE
  FOR EACH STATEMENT EXECUTE FUNCTION public.audit_statement_trigger();
CREATE TRIGGER audit_gradebook_column_groups_delete
  AFTER DELETE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS OLD_TABLE
  FOR EACH STATEMENT EXECUTE FUNCTION public.audit_statement_trigger();

-- Next.js cache tag invalidation, matching 20251228131640_cache_invalidation_triggers.sql.
CREATE TRIGGER invalidate_gradebook_column_groups_cache_insert
  AFTER INSERT ON public.gradebook_column_groups
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.invalidate_class_scoped_cache();
CREATE TRIGGER invalidate_gradebook_column_groups_cache_update
  AFTER UPDATE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS old_table NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.invalidate_class_scoped_cache();
CREATE TRIGGER invalidate_gradebook_column_groups_cache_delete
  AFTER DELETE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS old_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.invalidate_class_scoped_cache();

-- ---------------------------------------------------------------------------------------------
-- 4. The legacy heuristic, in SQL, used only by the backfill below
-- ---------------------------------------------------------------------------------------------
--
-- These two functions are a transcription of the `groupedColumns` memo. They exist so the
-- backfill can prove it reproduces what the browser did, and so routing a newly created column
-- can use the same rule the gradebook has always used. They do not run at render time.

CREATE OR REPLACE FUNCTION public.gradebook_column_base_group_name(p_slug text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  -- JS: const slugParts = col.slug.split("-");
  --     if (slugParts[0] === "assignment" && slugParts.length >= 3)
  --       baseGroupName = `${slugParts[0]}-${slugParts[1]}`;
  --     else baseGroupName = slugParts[0] || "other";
  --
  -- string_to_array('', '-') is {""} with array_length 1, which matches "".split("-") === [""].
  -- That empty first element is what the JS `|| "other"` catches.
  SELECT CASE
    WHEN parts[1] = 'assignment' AND array_length(parts, 1) >= 3
      THEN parts[1] || '-' || parts[2]
    WHEN COALESCE(parts[1], '') = ''
      THEN 'other'
    ELSE parts[1]
  END
  FROM (SELECT string_to_array(COALESCE(p_slug, ''), '-') AS parts) s;
$$;

COMMENT ON FUNCTION public.gradebook_column_base_group_name(text) IS
  'Transcription of the legacy slug-prefix heuristic. Used by the one-time backfill and by new-column routing, never at render time.';

CREATE OR REPLACE FUNCTION public.gradebook_column_group_display_name(p_base text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  -- JS uppercases index 0 only: `s.charAt(0).toUpperCase() + s.slice(1)`.
  -- Deliberately NOT initcap(), which would also uppercase after digits and underscores:
  -- initcap('mcq2go') is 'Mcq2Go', and initcap('a_b') is 'A_B'. The display name is what an
  -- instructor sees and renames from, so it has to match what they saw yesterday.
  SELECT CASE
    WHEN p_base = 'other' THEN 'Other'
    WHEN p_base LIKE 'assignment-%' THEN
      upper(left(split_part(p_base, '-', 2), 1)) || substr(split_part(p_base, '-', 2), 2)
    ELSE upper(left(p_base, 1)) || substr(p_base, 2)
  END;
$$;

-- ---------------------------------------------------------------------------------------------
-- 5. New columns on gradebook_columns
-- ---------------------------------------------------------------------------------------------

ALTER TABLE public.gradebook_columns
  ADD COLUMN IF NOT EXISTS gradebook_column_group_id bigint,
  ADD COLUMN IF NOT EXISTS position_in_group integer,
  ADD COLUMN IF NOT EXISTS weight numeric;

COMMENT ON COLUMN public.gradebook_columns.position_in_group IS
  'Position within gradebook_column_group_id. Replaces the former global sort_order; display order is (group.sort_order, position_in_group, id).';
COMMENT ON COLUMN public.gradebook_columns.weight IS
  'Relative share within this column''s group, read by weighted_total(). NULL means 1.';

-- ---------------------------------------------------------------------------------------------
-- 6. Phase one: reproduce today's grouping, exactly
-- ---------------------------------------------------------------------------------------------
--
-- The memo is a single pass that opens a new group when either the slug base changes or
-- sort_order skips a number. As a window function: mark each break, then running-sum the marks.
-- The sum starts at 1 because rn = 1 is always a break, which matches the JS incrementing
-- currentGroupIndex before its first use.

CREATE OR REPLACE VIEW public.gradebook_column_legacy_groups AS
WITH cols AS (
  SELECT gc.id,
         gc.gradebook_id,
         gc.class_id,
         gc.slug,
         gc.sort_order AS so,
         public.gradebook_column_base_group_name(gc.slug) AS base
    FROM public.gradebook_columns gc
),
seq AS (
  SELECT c.*,
         ROW_NUMBER() OVER w AS rn,
         LAG(c.so)   OVER w AS prev_so,
         LAG(c.base) OVER w AS prev_base
    FROM cols c
  WINDOW w AS (PARTITION BY c.gradebook_id ORDER BY c.so ASC, c.id ASC)
),
marked AS (
  SELECT s.*,
         CASE
           WHEN s.rn = 1                             THEN 1  -- JS: lastSortOrder === -1
           WHEN s.so <> s.prev_so + 1                THEN 1  -- JS: contiguity break
           WHEN s.base IS DISTINCT FROM s.prev_base  THEN 1  -- JS: prefix break
           ELSE 0
         END AS is_new_group
    FROM seq s
)
SELECT m.*,
       SUM(m.is_new_group) OVER (PARTITION BY m.gradebook_id
                                 ORDER BY m.so, m.id
                                 ROWS UNBOUNDED PRECEDING) AS group_index
  FROM marked m;

COMMENT ON VIEW public.gradebook_column_legacy_groups IS
  'Scaffolding for the 20260920120000 backfill. Dropped at the end of that migration.';

-- The default group first, so its slug cannot collide with a run slug. Run slugs always end in
-- '-<integer>'; 'ungrouped' does not.
INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name, slug, sort_order, is_default)
SELECT g.class_id, g.id, 'Ungrouped', 'ungrouped', 2147483647, true
  FROM public.gradebooks g
ON CONFLICT (gradebook_id, slug) DO NOTHING;

-- broadcast_gradebook_columns_change() loops over every student in the class and calls
-- safe_broadcast once per student per row. Backfilling a 200-column gradebook in a 300-student
-- class would emit 60,000 broadcast calls inside this transaction, so the trigger comes off for
-- the duration. Nobody is listening to a migration anyway.
ALTER TABLE public.gradebook_columns DISABLE TRIGGER broadcast_gradebook_columns_unified;

WITH ins AS (
  INSERT INTO public.gradebook_column_groups
         (class_id, gradebook_id, name, slug, sort_order, auto_assign_slug_base)
  SELECT DISTINCT ON (r.gradebook_id, r.group_index)
         r.class_id,
         r.gradebook_id,
         public.gradebook_column_group_display_name(r.base),
         r.base || '-' || r.group_index,
         (r.group_index - 1)::integer,
         r.base
    FROM public.gradebook_column_legacy_groups r
   ORDER BY r.gradebook_id, r.group_index, r.so, r.id
  RETURNING id, gradebook_id, slug
)
UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = ins.id
  FROM public.gradebook_column_legacy_groups r
  JOIN ins ON ins.gradebook_id = r.gradebook_id
          AND ins.slug = r.base || '-' || r.group_index
 WHERE gc.id = r.id;

-- Position within the group, preserving the order the columns were already in.
UPDATE public.gradebook_columns gc
   SET position_in_group = sub.pos
  FROM (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY gradebook_column_group_id
                              ORDER BY sort_order, id) - 1 AS pos
      FROM public.gradebook_columns
     WHERE gradebook_column_group_id IS NOT NULL
  ) sub
 WHERE gc.id = sub.id;

ALTER TABLE public.gradebook_columns ENABLE TRIGGER broadcast_gradebook_columns_unified;

-- ---------------------------------------------------------------------------------------------
-- 7. Phase one proof: the backfill reproduces the heuristic exactly
-- ---------------------------------------------------------------------------------------------
--
-- Three assertions, all fatal. If any of them fires the deploy stops rather than shipping a
-- gradebook that looks subtly different from the one the instructor had yesterday.
--
-- Group ids are arbitrary, so equality of ids is the wrong test. The right one is that the two
-- partitions of the same column set are identical: every legacy run maps onto exactly one new
-- group, and every new group onto exactly one legacy run.

DO $$
DECLARE
  v_ungrouped     integer;
  v_order_diffs   integer;
  v_split_runs    integer;
  v_merged_runs   integer;
  v_name_diffs    integer;
  v_dupe_orders   integer;
BEGIN
  SELECT count(*) INTO v_ungrouped
    FROM public.gradebook_columns
   WHERE gradebook_column_group_id IS NULL OR position_in_group IS NULL;
  IF v_ungrouped > 0 THEN
    RAISE EXCEPTION 'backfill: % columns were left without a group or a position', v_ungrouped;
  END IF;

  -- The strong one. Rebuild global order from the two levels and require it to equal the order
  -- the columns were already in, row for row. This is what lets the PR claim that nothing moved.
  SELECT count(*) INTO v_order_diffs
    FROM (
      SELECT ROW_NUMBER() OVER (PARTITION BY c.gradebook_id
                                ORDER BY c.sort_order, c.id) AS old_pos,
             ROW_NUMBER() OVER (PARTITION BY c.gradebook_id
                                ORDER BY g.sort_order, c.position_in_group, c.id) AS new_pos
        FROM public.gradebook_columns c
        JOIN public.gradebook_column_groups g ON g.id = c.gradebook_column_group_id
    ) t
   WHERE t.old_pos <> t.new_pos;
  IF v_order_diffs > 0 THEN
    RAISE EXCEPTION 'backfill: % columns would render in a different position than before', v_order_diffs;
  END IF;

  -- No legacy run got split across two groups.
  SELECT count(*) INTO v_split_runs
    FROM (
      SELECT count(DISTINCT gc.gradebook_column_group_id) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       GROUP BY r.gradebook_id, r.group_index
    ) x
   WHERE x.n <> 1;

  -- No two legacy runs got merged into one group.
  SELECT count(*) INTO v_merged_runs
    FROM (
      SELECT count(DISTINCT (r.gradebook_id, r.group_index)) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       GROUP BY gc.gradebook_column_group_id
    ) x
   WHERE x.n <> 1;

  IF v_split_runs > 0 OR v_merged_runs > 0 THEN
    RAISE EXCEPTION 'backfill: partition mismatch (% runs split, % runs merged)',
      v_split_runs, v_merged_runs;
  END IF;

  -- And the header text is the text the browser was rendering.
  SELECT count(*) INTO v_name_diffs
    FROM public.gradebook_column_legacy_groups r
    JOIN public.gradebook_columns gc ON gc.id = r.id
    JOIN public.gradebook_column_groups g ON g.id = gc.gradebook_column_group_id
   WHERE g.name IS DISTINCT FROM public.gradebook_column_group_display_name(r.base);
  IF v_name_diffs > 0 THEN
    RAISE EXCEPTION 'backfill: % columns sit under a differently-named header than before', v_name_diffs;
  END IF;

  -- Not fatal, and not fixable. Where two columns share a sort_order the browser's order came
  -- from whatever sequence PostgREST happened to return, which is undefined; SQL tie-breaks on
  -- id. For those rows "identical to before" is not a claim anyone can make, so say so out loud
  -- rather than pretending the proof above covers them.
  SELECT count(*) INTO v_dupe_orders
    FROM (
      SELECT gradebook_id, sort_order
        FROM public.gradebook_columns
       GROUP BY gradebook_id, sort_order
      HAVING count(*) > 1
    ) d;
  IF v_dupe_orders > 0 THEN
    RAISE WARNING 'backfill: % duplicate (gradebook_id, sort_order) pairs; browser order for those was undefined, SQL tie-broke on id', v_dupe_orders;
  END IF;

  RAISE NOTICE 'backfill phase one: reproduced the legacy grouping for % columns in % groups',
    (SELECT count(*) FROM public.gradebook_columns),
    (SELECT count(*) FROM public.gradebook_column_groups WHERE NOT is_default);
END $$;

-- ---------------------------------------------------------------------------------------------
-- 8. Phase two: correct the cases the heuristic gets wrong
-- ---------------------------------------------------------------------------------------------
--
-- Phase one proved we can reproduce the old grouping. This phase changes it, on purpose, in four
-- named ways. Every column any of them touches is recorded in a ledger, and the check at the end
-- asserts that nothing outside the ledger moved. A correction that quietly changed something else
-- would fail the deploy.
--
-- Each rule is general. None of them looks for a slug from the seed.

CREATE TABLE public._cg_correction_ledger (
  column_id  bigint PRIMARY KEY,
  correction text NOT NULL
);

-- --- C1. A family split in two by a hole in sort_order ----------------------------------------
--
-- Deleting a column leaves a gap, and the heuristic reads a gap as the end of a group. So a
-- gradebook that once had quiz-1..5 and lost quiz-3 renders two headers, both reading "Quiz".
-- They also collapse together, because the client keys collapse state on the header text, so the
-- user sees one name, two headers, and a single toggle that moves both.
--
-- Contiguity of an integer was never what made those columns a family. Sharing the slug base was.
-- Merge groups that share a base, keeping the leftmost, and keep the members in the order they
-- were already in.

CREATE TEMP TABLE _cg_merge_map AS
WITH fams AS (
  SELECT gradebook_id,
         auto_assign_slug_base,
         (array_agg(id ORDER BY sort_order, id))[1] AS keep_id,
         array_agg(id) AS member_group_ids
    FROM public.gradebook_column_groups
   WHERE auto_assign_slug_base IS NOT NULL AND NOT is_default
   GROUP BY gradebook_id, auto_assign_slug_base
  HAVING count(*) > 1
)
SELECT gc.id AS column_id,
       f.keep_id AS new_group_id,
       ROW_NUMBER() OVER (PARTITION BY f.keep_id ORDER BY g.sort_order, gc.position_in_group, gc.id) - 1
         AS new_position
  FROM fams f
  JOIN public.gradebook_column_groups g
    ON g.id = ANY (f.member_group_ids)
  JOIN public.gradebook_columns gc
    ON gc.gradebook_column_group_id = g.id;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT column_id, 'C1 merged a family that a deleted column had split in two'
  FROM _cg_merge_map
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = m.new_group_id,
       position_in_group         = m.new_position
  FROM _cg_merge_map m
 WHERE gc.id = m.column_id;

-- The groups the merge emptied.
DELETE FROM public.gradebook_column_groups g
 WHERE NOT g.is_default
   AND NOT EXISTS (SELECT 1 FROM public.gradebook_columns c
                    WHERE c.gradebook_column_group_id = g.id);

-- --- C2. Columns classified from their slug rather than their assignment ----------------------
--
-- The heuristic decides a column is assignment-backed by reading its slug, and decides which
-- kind of assignment by taking the second dash-separated token. Both facts are already in the
-- database. public.assignments has a gradebook_column_id foreign key pointing straight at the
-- column, minutes_due_after_lab that is non-null exactly for labs, and group_config.
--
-- Reading the foreign key instead of the string fixes two things at once.
--
-- A column slugged `assignment-final` has only two tokens, so it misses the `>= 3` branch and
-- falls back to the bare base `assignment`, landing under a header reading "Assignment" that is
-- a different group from the homework family's header, which also reads "Assignment". Two groups,
-- one name, and collapse state keyed on the name, so they toggle together from opposite ends of
-- the gradebook.
--
-- The deeper problem is that a slug is not evidence. A column named `assignment-final` that no
-- assignment row points at is not an assignment column; it is a manually created column someone
-- named that way. Stated policy: assignment-backed means an assignments row references it. A
-- column that merely looks assignment-backed is moved out into its own group, named after the
-- column, because the database says it is not what its slug claims.

-- C2a: genuine assignment columns, grouped by what kind of assignment they are.
CREATE TEMP TABLE _cg_assignment_kind AS
SELECT gc.id AS column_id,
       gc.gradebook_id,
       gc.class_id,
       CASE
         WHEN a.minutes_due_after_lab IS NOT NULL      THEN 'assignment-lab'
         WHEN a.group_config <> 'individual'           THEN 'assignment-group'
         ELSE                                               'assignment-individual'
       END AS kind
  FROM public.gradebook_columns gc
  JOIN public.assignments a ON a.gradebook_column_id = gc.id;

-- C2b: columns whose slug claims an assignment that does not exist.
CREATE TEMP TABLE _cg_slug_pretenders AS
SELECT gc.id AS column_id, gc.gradebook_id, gc.class_id, gc.name
  FROM public.gradebook_columns gc
 WHERE gc.slug LIKE 'assignment-%'
   AND NOT EXISTS (SELECT 1 FROM public.assignments a WHERE a.gradebook_column_id = gc.id);

-- Get-or-create, appending at the right-hand end of the gradebook. Scaffolding; dropped below.
CREATE OR REPLACE FUNCTION public._cg_ensure_group(
  p_gradebook_id bigint, p_class_id bigint, p_slug text, p_name text, p_auto_base text)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_id bigint;
BEGIN
  SELECT id INTO v_id
    FROM public.gradebook_column_groups
   WHERE gradebook_id = p_gradebook_id AND slug = p_slug;
  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  INSERT INTO public.gradebook_column_groups
         (class_id, gradebook_id, name, slug, sort_order, auto_assign_slug_base)
  SELECT p_class_id, p_gradebook_id, p_name, p_slug,
         COALESCE((SELECT MAX(sort_order) + 1
                     FROM public.gradebook_column_groups
                    WHERE gradebook_id = p_gradebook_id AND NOT is_default), 0),
         p_auto_base
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;

-- C2a: move each genuine assignment column into the group for its kind.
CREATE TEMP TABLE _cg_c2a_targets AS
SELECT k.column_id,
       public._cg_ensure_group(
         k.gradebook_id, k.class_id, k.kind,
         CASE k.kind
           WHEN 'assignment-lab'   THEN 'Labs'
           WHEN 'assignment-group' THEN 'Group Assignments'
           ELSE                         'Assignments'
         END,
         k.kind) AS new_group_id
  FROM _cg_assignment_kind k;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT t.column_id, 'C2 classified from the assignments row instead of the slug'
  FROM _cg_c2a_targets t
  JOIN public.gradebook_columns gc ON gc.id = t.column_id
 WHERE gc.gradebook_column_group_id IS DISTINCT FROM t.new_group_id
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = t.new_group_id
  FROM _cg_c2a_targets t
 WHERE gc.id = t.column_id;

-- C2b: a column whose slug claims an assignment nothing backs gets its own group, named after
-- the column rather than after the lie in its slug.
CREATE TEMP TABLE _cg_c2b_targets AS
SELECT p.column_id,
       public._cg_ensure_group(
         p.gradebook_id, p.class_id,
         'column-' || p.column_id::text, p.name, NULL) AS new_group_id
  FROM _cg_slug_pretenders p;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT t.column_id, 'C2 slug claimed an assignment that does not exist; moved out of the assignment group'
  FROM _cg_c2b_targets t
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = t.new_group_id
  FROM _cg_c2b_targets t
 WHERE gc.id = t.column_id;

-- --- C3. Computed columns that read the same inputs ------------------------------------------
--
-- Three columns can share a concept and no prefix at all. `meets-expectations`,
-- `approaching-expectations` and `does-not-meet-expectations` each count the same twelve skill
-- columns at a different threshold. The heuristic gives them the bases `meets`, `approaching`
-- and `does`, so they scatter into three groups of one, which is the milder form of the case
-- CS 2100 makes unmanageable.
--
-- The database already knows they belong together. gradebook_columns.dependencies records which
-- columns a computed column is built from, and the grouping code has never read it. Two computed
-- columns that read exactly the same set of inputs are grouped.
--
-- Limitation, stated rather than papered over: this fires only where dependencies is populated.
-- Columns whose score_expression uses a glob and were inserted without dependencies being
-- materialised, which is how `total-labs` and `labs-drop-lowest` arrive from the seeder, are left
-- where the heuristic put them. Fixing that means materialising dependencies for glob
-- expressions, which is a different change from this one.

CREATE TEMP TABLE _cg_dep_cohorts AS
WITH deps AS (
  SELECT gc.id AS column_id,
         gc.gradebook_id,
         gc.class_id,
         (SELECT array_agg(x ORDER BY x)
            FROM jsonb_array_elements_text(gc.dependencies -> 'gradebook_columns') AS t(x)
         ) AS dep_set
    FROM public.gradebook_columns gc
   WHERE gc.dependencies ? 'gradebook_columns'
     AND jsonb_array_length(gc.dependencies -> 'gradebook_columns') >= 2
)
SELECT gradebook_id, class_id, dep_set,
       array_agg(column_id ORDER BY column_id) AS column_ids
  FROM deps
 WHERE dep_set IS NOT NULL
 GROUP BY gradebook_id, class_id, dep_set
HAVING count(*) > 1;

-- The longest prefix every one of a set of names starts with. The lexicographic min and max are
-- enough: any prefix shared by those two is shared by everything between them. Trailing
-- separators and the first differing digit are trimmed, so "AI Usage Log 1" and "AI Usage Log 2"
-- give "AI Usage Log". Scaffolding; dropped below.
CREATE OR REPLACE FUNCTION public._cg_common_name_prefix(p_names text[])
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  WITH b AS (
    SELECT min(n) AS lo, max(n) AS hi, array_length(p_names, 1) AS cnt
      FROM unnest(p_names) AS t(n)
  ),
  l AS (
    SELECT b.lo, b.cnt,
           (SELECT COALESCE(max(i), 0)
              FROM generate_series(1, least(length(b.lo), length(b.hi))) AS i
             WHERE left(b.lo, i) = left(b.hi, i)) AS lcp
      FROM b
  )
  SELECT CASE
           -- A group of one is best described by the column in it. The heuristic could only ever
           -- offer a capitalised slug fragment, which is how a column called
           -- "Labs (drop lowest 2)" ended up under a header reading "Labs", next to the actual
           -- labs.
           WHEN l.cnt = 1 THEN NULLIF(btrim(l.lo), '')
           WHEN l.cnt >= 2 AND l.lcp >= 3
             THEN NULLIF(btrim(regexp_replace(left(l.lo, l.lcp), '[[:space:][:punct:]]*[0-9]*[[:space:][:punct:]]*$', '')), '')
           ELSE NULL
         END
    FROM l;
$$;

-- C3 apply: one group per cohort, but only where the cohort is currently scattered.
--
-- Naming, in order of preference: the prefix the member names share; failing that, the name of
-- the group the inputs live in, so twelve columns grouped as "Skill" give their three summary
-- columns the header "Skill Summary"; failing that, a flat label.
CREATE TEMP TABLE _cg_c3_targets AS
WITH scattered AS (
  SELECT c.*,
         (SELECT count(DISTINCT gc.gradebook_column_group_id)
            FROM public.gradebook_columns gc
           WHERE gc.id = ANY (c.column_ids)) AS groups_now,
         (SELECT public._cg_common_name_prefix(array_agg(gc.name))
            FROM public.gradebook_columns gc
           WHERE gc.id = ANY (c.column_ids)) AS common_name,
         (SELECT CASE WHEN count(DISTINCT dep.gradebook_column_group_id) = 1
                      THEN max(dg.name) END
            FROM unnest(c.dep_set) AS d(dep_id)
            JOIN public.gradebook_columns dep
              ON dep.id = d.dep_id::bigint
            JOIN public.gradebook_column_groups dg
              ON dg.id = dep.gradebook_column_group_id) AS dep_group_name
    FROM _cg_dep_cohorts c
)
SELECT unnest(s.column_ids) AS column_id,
       public._cg_ensure_group(
         s.gradebook_id, s.class_id,
         'derived-' || md5(s.dep_set::text),
         COALESCE(s.common_name,
                  NULLIF(s.dep_group_name, '') || ' Summary',
                  'Computed'),
         NULL) AS new_group_id
  FROM scattered s
 WHERE s.groups_now > 1;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT t.column_id, 'C3 grouped with the other columns that read the same inputs'
  FROM _cg_c3_targets t
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = t.new_group_id
  FROM _cg_c3_targets t
 WHERE gc.id = t.column_id;

-- --- C4. Name the group after what the instructor called the columns ---------------------------
--
-- The heuristic builds a header by uppercasing the first letter of a slug fragment, so a pair of
-- columns named "AI Usage Log 1" and "AI Usage Log 2" ends up under a header reading "Ai". The
-- instructor already wrote the name; it is in gradebook_columns.name. Use the longest prefix the
-- members share, where there is one, in preference to a substring of a slug.

WITH prefixes AS (
  SELECT g.id AS group_id,
         g.name AS current_name,
         public._cg_common_name_prefix(array_agg(gc.name)) AS common_name
    FROM public.gradebook_column_groups g
    JOIN public.gradebook_columns gc ON gc.gradebook_column_group_id = g.id
   WHERE NOT g.is_default
     -- The three groups C2 creates are named for a category of assignment and will receive
     -- every assignment made from here on. A course with one lab so far would otherwise get a
     -- header reading "Lab 1 (Group)", which stops being true the moment a second lab exists.
     AND g.slug NOT IN ('assignment-lab', 'assignment-individual', 'assignment-group')
   GROUP BY g.id, g.name
)
INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT gc.id, 'C4 header renamed from the column names instead of the slug'
  FROM prefixes p
  JOIN public.gradebook_columns gc ON gc.gradebook_column_group_id = p.group_id
 WHERE p.common_name IS NOT NULL
   AND p.common_name IS DISTINCT FROM p.current_name
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_column_groups g
   SET name = p.common_name
  FROM (
    SELECT g2.id AS group_id,
           g2.name AS current_name,
           public._cg_common_name_prefix(array_agg(gc.name)) AS common_name
      FROM public.gradebook_column_groups g2
      JOIN public.gradebook_columns gc ON gc.gradebook_column_group_id = g2.id
     WHERE NOT g2.is_default
       AND g2.slug NOT IN ('assignment-lab', 'assignment-individual', 'assignment-group')
     GROUP BY g2.id, g2.name
  ) p
 WHERE g.id = p.group_id
   AND p.common_name IS NOT NULL
   AND p.common_name IS DISTINCT FROM p.current_name;

-- --- Tidy up ordering after the corrections ---------------------------------------------------

-- Drop groups the corrections emptied.
DELETE FROM public.gradebook_column_groups g
 WHERE NOT g.is_default
   AND NOT EXISTS (SELECT 1 FROM public.gradebook_columns c
                    WHERE c.gradebook_column_group_id = g.id);

-- Positions dense within each group, preserving relative order.
UPDATE public.gradebook_columns gc
   SET position_in_group = sub.pos
  FROM (
    SELECT id,
           -- Ordered by the legacy global sort_order, so a column moved between groups by C2 or
           -- C3 lands where an instructor would expect rather than at whatever index it held in
           -- the group it came from.
           ROW_NUMBER() OVER (PARTITION BY gradebook_column_group_id
                              ORDER BY sort_order, id) - 1 AS pos
      FROM public.gradebook_columns
     WHERE gradebook_column_group_id IS NOT NULL
  ) sub
 WHERE gc.id = sub.id
   AND gc.position_in_group IS DISTINCT FROM sub.pos;

-- Groups dense within each gradebook, keeping left-to-right reading order and parking the
-- default group at the right-hand end where it is out of the way until something needs it.
-- Keyed on the smallest legacy sort_order in each group, which is still the global order the
-- columns were in. position_in_group cannot be used here: it restarts at 0 in every group.
UPDATE public.gradebook_column_groups g
   SET sort_order = sub.pos
  FROM (
    SELECT gg.id,
           ROW_NUMBER() OVER (
             PARTITION BY gg.gradebook_id
             ORDER BY gg.is_default,
                      COALESCE((SELECT min(c.sort_order)
                                  FROM public.gradebook_columns c
                                 WHERE c.gradebook_column_group_id = gg.id),
                               2147483647),
                      gg.sort_order, gg.id) - 1 AS pos
      FROM public.gradebook_column_groups gg
  ) sub
 WHERE g.id = sub.id
   AND g.sort_order IS DISTINCT FROM sub.pos;

-- ---------------------------------------------------------------------------------------------
-- 9. Phase two proof: only the ledgered columns moved
-- ---------------------------------------------------------------------------------------------
--
-- Restrict both partitions to columns no correction touched, and require them to still agree.
-- A correction that reached further than its description says fails the deploy here.

DO $$
DECLARE
  v_split   integer;
  v_merged  integer;
  v_touched integer;
  v_total   integer;
BEGIN
  SELECT count(*) INTO v_split
    FROM (
      SELECT count(DISTINCT gc.gradebook_column_group_id) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       WHERE NOT EXISTS (SELECT 1 FROM public._cg_correction_ledger l WHERE l.column_id = r.id)
       GROUP BY r.gradebook_id, r.group_index
    ) x
   WHERE x.n <> 1;

  SELECT count(*) INTO v_merged
    FROM (
      SELECT count(DISTINCT (r.gradebook_id, r.group_index)) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       WHERE NOT EXISTS (SELECT 1 FROM public._cg_correction_ledger l WHERE l.column_id = r.id)
       GROUP BY gc.gradebook_column_group_id
    ) x
   WHERE x.n <> 1;

  IF v_split > 0 OR v_merged > 0 THEN
    RAISE EXCEPTION 'corrections: % untouched runs split and % untouched runs merged; a correction reached further than it claims',
      v_split, v_merged;
  END IF;

  SELECT count(*) INTO v_touched FROM public._cg_correction_ledger;
  SELECT count(*) INTO v_total   FROM public.gradebook_columns;
  RAISE NOTICE 'corrections: % of % columns regrouped; the rest are exactly where the heuristic had them',
    v_touched, v_total;
END $$;

-- A readable record of what changed and why, for the PR and for anyone reading this later.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT l.correction, count(*) AS n
      FROM public._cg_correction_ledger l
     GROUP BY l.correction
     ORDER BY count(*) DESC
  LOOP
    RAISE NOTICE 'correction applied to % column(s): %', r.n, r.correction;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------------------------
-- 10. Lock the shape in
-- ---------------------------------------------------------------------------------------------

ALTER TABLE public.gradebook_columns
  ALTER COLUMN gradebook_column_group_id SET NOT NULL,
  ALTER COLUMN position_in_group SET NOT NULL;

-- A sentinel default, so that a caller who does not care where the column lands can leave it out
-- and the enforce trigger will append it to the end of its group. The column stays NOT NULL: a
-- BEFORE INSERT trigger runs before NOT NULL is checked, so the trigger always gets to fill it.
-- The default also makes the generated TypeScript mark the field optional, which is the truth;
-- without it the types claim every insert must state a position when the database does not
-- require one.
ALTER TABLE public.gradebook_columns
  ALTER COLUMN position_in_group SET DEFAULT -1;

-- The composite reference is the point. Pointing at (id, gradebook_id) rather than at id alone
-- means a column filed under another gradebook's group is not a bug to be caught in review, it
-- is a row Postgres refuses to write.
ALTER TABLE public.gradebook_columns
  ADD CONSTRAINT gradebook_columns_group_fk
  FOREIGN KEY (gradebook_column_group_id, gradebook_id)
  REFERENCES public.gradebook_column_groups (id, gradebook_id)
  ON DELETE RESTRICT;

-- Until now nothing enforced uniqueness of a column's position. The old trigger shifted
-- neighbours to keep sort_order unique, and that procedure was the only thing standing between
-- the gradebook and two columns claiming the same slot. Deferrable because a swap collides
-- halfway through.
ALTER TABLE public.gradebook_columns
  ADD CONSTRAINT gradebook_columns_position_key
  UNIQUE (gradebook_column_group_id, position_in_group) DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------------------------
-- 11. Drop the old global order
-- ---------------------------------------------------------------------------------------------
--
-- Dropped rather than renamed or reinterpreted. sort_order is read as a global sequence in a lot
-- of places, and a reinterpretation would have left every one of them returning a plausible,
-- wrongly ordered result. Dropping turns each one into an error at query time, and the
-- regenerated types turn the TypeScript half into a build failure.

DROP VIEW IF EXISTS public.gradebook_column_legacy_groups;

-- The enforce trigger names sort_order in its UPDATE OF list, which is a hard dependency, so it
-- has to come off before the column can go. 20260920120100 recreates it against
-- position_in_group, scoped to the group rather than the gradebook.
DROP TRIGGER IF EXISTS gradebook_columns_enforce_sort_order_tr ON public.gradebook_columns;

ALTER TABLE public.gradebook_columns DROP COLUMN sort_order;

-- Scaffolding, gone.
DROP FUNCTION IF EXISTS public._cg_ensure_group(bigint, bigint, text, text, text);
DROP FUNCTION IF EXISTS public._cg_common_name_prefix(text[]);
DROP TABLE IF EXISTS public._cg_correction_ledger;

-- ---------------------------------------------------------------------------------------------
-- 12. Reading the two levels back as one order
-- ---------------------------------------------------------------------------------------------
--
-- security_invoker is load-bearing, not decoration. A view runs as its owner by default, which
-- would hand every caller every course's columns straight past the policies above. The repo
-- already sets it on a dozen views, including submissions_with_grades_for_assignment_nice.

CREATE OR REPLACE VIEW public.gradebook_columns_ordered
WITH (security_invoker = 'true') AS
SELECT c.*,
       g.sort_order AS group_sort_order,
       g.name       AS group_name,
       g.slug       AS group_slug,
       g.weight     AS group_weight,
       ROW_NUMBER() OVER (PARTITION BY c.gradebook_id
                          ORDER BY g.sort_order, c.position_in_group, c.id) - 1 AS display_order
  FROM public.gradebook_columns c
  JOIN public.gradebook_column_groups g ON g.id = c.gradebook_column_group_id;

COMMENT ON VIEW public.gradebook_columns_ordered IS
  'gradebook_columns with its group joined and the two ordering levels flattened into display_order.';

GRANT SELECT ON public.gradebook_columns_ordered TO authenticated;
GRANT SELECT ON public.gradebook_columns_ordered TO service_role;

-- The old covering index carried sort_order, which no longer exists. The hot path is now the
-- join to the group plus the two-level sort.
DROP INDEX IF EXISTS public.idx_gradebook_columns_id_covering;
CREATE INDEX IF NOT EXISTS idx_gradebook_columns_group_position
  ON public.gradebook_columns (gradebook_column_group_id, position_in_group) INCLUDE (id);
CREATE INDEX IF NOT EXISTS idx_gradebook_columns_gradebook_group
  ON public.gradebook_columns (gradebook_id, gradebook_column_group_id);
