DO $$
DECLARE
  v_nulls integer;
BEGIN
  UPDATE public.gradebook_columns gc
     SET sort_order = sub.new_order
    FROM (
      SELECT id,
             ROW_NUMBER() OVER (PARTITION BY gradebook_id ORDER BY id) - 1
               + COALESCE((SELECT MAX(sort_order) + 1
                             FROM public.gradebook_columns x
                            WHERE x.gradebook_id = gradebook_columns.gradebook_id
                              AND x.sort_order IS NOT NULL), 0) AS new_order
        FROM public.gradebook_columns
       WHERE sort_order IS NULL
    ) sub
   WHERE gc.id = sub.id;

  SELECT count(*) INTO v_nulls FROM public.gradebook_columns WHERE sort_order IS NULL;
  IF v_nulls > 0 THEN
    RAISE EXCEPTION 'gradebook_column_groups: % columns still have a NULL sort_order', v_nulls;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.gradebook_column_groups (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  class_id     bigint NOT NULL REFERENCES public.classes(id)    ON DELETE CASCADE,
  gradebook_id bigint NOT NULL REFERENCES public.gradebooks(id) ON DELETE CASCADE,
  name         text NOT NULL,
  slug         text NOT NULL,
  description  text,
  sort_order   integer NOT NULL,
  is_default   boolean NOT NULL DEFAULT false,
  auto_assign_slug_base text,
  CONSTRAINT gradebook_column_groups_slug_key
    UNIQUE (gradebook_id, slug),
  CONSTRAINT gradebook_column_groups_id_gradebook_key
    UNIQUE (id, gradebook_id),
  CONSTRAINT gradebook_column_groups_order_key
    UNIQUE (gradebook_id, sort_order) DEFERRABLE INITIALLY DEFERRED,
  -- The default group is pinned last. Pinning it at a sentinel rather than at count(groups)
  -- keeps MAX(sort_order) + 1 over the other groups from ever landing on it.
  CONSTRAINT gradebook_column_groups_default_last_chk
    CHECK (is_default = (sort_order = 2147483647))
);

COMMENT ON TABLE public.gradebook_column_groups IS
  'A gradebook column group. Replaces the slug-prefix heuristic that used to compute groups in the browser on every render.';
COMMENT ON COLUMN public.gradebook_column_groups.sort_order IS
  'Position among this gradebook''s groups. Columns are ordered within a group by gradebook_columns.position_in_group. The default group is always 2147483647.';
COMMENT ON COLUMN public.gradebook_column_groups.auto_assign_slug_base IS
  'Legacy slug base that routes new columns here. NULL means the group does not auto-receive columns.';

CREATE UNIQUE INDEX IF NOT EXISTS gradebook_column_groups_one_default
  ON public.gradebook_column_groups (gradebook_id) WHERE is_default;
CREATE INDEX IF NOT EXISTS gradebook_column_groups_auto_assign_idx
  ON public.gradebook_column_groups (gradebook_id, auto_assign_slug_base)
  WHERE auto_assign_slug_base IS NOT NULL;
CREATE INDEX IF NOT EXISTS gradebook_column_groups_class_id_idx
  ON public.gradebook_column_groups (class_id);

ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE public.gradebook_column_groups TO authenticated;
GRANT ALL    ON TABLE public.gradebook_column_groups TO service_role;

DROP POLICY IF EXISTS "instructors manage column groups" ON public.gradebook_column_groups;
CREATE POLICY "instructors manage column groups"
  ON public.gradebook_column_groups
  AS PERMISSIVE FOR ALL TO authenticated
  USING      (public.authorizeforclassinstructor(class_id))
  WITH CHECK (public.authorizeforclassinstructor(class_id));

DROP TRIGGER IF EXISTS set_updated_at_on_gradebook_column_groups ON public.gradebook_column_groups;
CREATE TRIGGER set_updated_at_on_gradebook_column_groups
  BEFORE UPDATE ON public.gradebook_column_groups
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Statement-level: a renumber touches every group in a gradebook, and a row-level trigger
-- would repeat the per-student loop once per group.
CREATE OR REPLACE FUNCTION public._broadcast_gradebook_column_group_rows(
  p_operation text, p_rows jsonb, p_students_only boolean DEFAULT false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  r jsonb;
  v_class_id bigint;
  v_students_class_id bigint;
  v_students uuid[];
  v_profile_id uuid;
  v_payload jsonb;
  v_student_data jsonb;
BEGIN
  FOR r IN SELECT value FROM jsonb_array_elements(COALESCE(p_rows, '[]'::jsonb))
  LOOP
    v_class_id := (r->>'class_id')::bigint;
    CONTINUE WHEN v_class_id IS NULL;

    v_payload := jsonb_build_object(
      'type', 'table_change',
      'operation', p_operation,
      'table', 'gradebook_column_groups',
      'row_id', (r->>'id')::bigint,
      'data', r,
      'class_id', v_class_id,
      'target_audience', 'staff',
      'timestamp', NOW()
    );

    IF NOT p_students_only THEN
      PERFORM public.safe_broadcast(v_payload, 'broadcast', 'class:' || v_class_id || ':staff', true);
    END IF;

    -- Students get a group only once it holds a column they can see, matching the SELECT policy.
    IF p_operation = 'DELETE' THEN
      v_student_data := jsonb_build_object('id', r->'id', 'class_id', r->'class_id', 'gradebook_id', r->'gradebook_id');
    ELSIF EXISTS (
      SELECT 1 FROM public.gradebook_columns c
       WHERE c.gradebook_column_group_id = (r->>'id')::bigint
         AND (NOT COALESCE(c.instructor_only, false) OR c.released)
    ) THEN
      v_student_data := r;
    ELSE
      CONTINUE;
    END IF;

    IF v_students_class_id IS DISTINCT FROM v_class_id THEN
      SELECT ARRAY(
        SELECT ur.private_profile_id FROM public.user_roles ur
         WHERE ur.class_id = v_class_id AND ur.role = 'student'
      ) INTO v_students;
      v_students_class_id := v_class_id;
    END IF;

    v_payload := v_payload || jsonb_build_object('target_audience', 'user', 'data', v_student_data);
    FOREACH v_profile_id IN ARRAY v_students
    LOOP
      PERFORM public.safe_broadcast(
        v_payload, 'broadcast', 'class:' || v_class_id || ':user:' || v_profile_id, true);
    END LOOP;
  END LOOP;
END $$;

REVOKE ALL ON FUNCTION public._broadcast_gradebook_column_group_rows(text, jsonb, boolean) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.broadcast_gradebook_column_groups_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM public._broadcast_gradebook_column_group_rows(
      TG_OP, (SELECT jsonb_agg(to_jsonb(o) ORDER BY o.class_id) FROM old_table o));
  ELSE
    PERFORM public._broadcast_gradebook_column_group_rows(
      TG_OP, (SELECT jsonb_agg(to_jsonb(n) ORDER BY n.class_id) FROM new_table n));
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS broadcast_gradebook_column_groups_unified ON public.gradebook_column_groups;
DROP TRIGGER IF EXISTS broadcast_gradebook_column_groups_insert ON public.gradebook_column_groups;
CREATE TRIGGER broadcast_gradebook_column_groups_insert
  AFTER INSERT ON public.gradebook_column_groups
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();
DROP TRIGGER IF EXISTS broadcast_gradebook_column_groups_update ON public.gradebook_column_groups;
CREATE TRIGGER broadcast_gradebook_column_groups_update
  AFTER UPDATE ON public.gradebook_column_groups
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();
DROP TRIGGER IF EXISTS broadcast_gradebook_column_groups_delete ON public.gradebook_column_groups;
CREATE TRIGGER broadcast_gradebook_column_groups_delete
  AFTER DELETE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS old_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();

CREATE TRIGGER audit_gradebook_column_groups_insert
  AFTER INSERT ON public.gradebook_column_groups
  REFERENCING NEW TABLE AS NEW_TABLE
  FOR EACH STATEMENT EXECUTE FUNCTION public.audit_statement_trigger();
CREATE TRIGGER audit_gradebook_column_groups_update
  AFTER UPDATE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS OLD_TABLE NEW TABLE AS NEW_TABLE
  FOR EACH STATEMENT EXECUTE FUNCTION public.audit_statement_trigger();
CREATE TRIGGER audit_gradebook_column_groups_delete
  AFTER DELETE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS OLD_TABLE
  FOR EACH STATEMENT EXECUTE FUNCTION public.audit_statement_trigger();

CREATE TRIGGER invalidate_gradebook_column_groups_cache_insert
  AFTER INSERT ON public.gradebook_column_groups
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.invalidate_class_scoped_cache();
CREATE TRIGGER invalidate_gradebook_column_groups_cache_update
  AFTER UPDATE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS old_table NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.invalidate_class_scoped_cache();
CREATE TRIGGER invalidate_gradebook_column_groups_cache_delete
  AFTER DELETE ON public.gradebook_column_groups
  REFERENCING OLD TABLE AS old_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.invalidate_class_scoped_cache();

CREATE OR REPLACE FUNCTION public.gradebook_column_base_group_name(p_slug text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN parts[1] = 'assignment' AND array_length(parts, 1) >= 3
      THEN parts[1] || '-' || parts[2]
    WHEN COALESCE(parts[1], '') = ''
      THEN 'other'
    ELSE parts[1]
  END
  FROM (SELECT string_to_array(COALESCE(p_slug, ''), '-') AS parts) s;
$$;

COMMENT ON FUNCTION public.gradebook_column_base_group_name(text) IS
  'Transcription of the legacy slug-prefix heuristic. Used by the one-time backfill and by new-column routing, never at render time.';

CREATE OR REPLACE FUNCTION public.gradebook_column_group_display_name(p_base text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_base = 'other' THEN 'Other'
    WHEN p_base LIKE 'assignment-%' THEN
      upper(left(split_part(p_base, '-', 2), 1)) || substr(split_part(p_base, '-', 2), 2)
    ELSE upper(left(p_base, 1)) || substr(p_base, 2)
  END;
$$;

ALTER TABLE public.gradebook_columns
  ADD COLUMN IF NOT EXISTS gradebook_column_group_id bigint,
  ADD COLUMN IF NOT EXISTS position_in_group integer;

DROP POLICY IF EXISTS "everyone in class can view column groups" ON public.gradebook_column_groups;
CREATE POLICY "everyone in class can view column groups"
  ON public.gradebook_column_groups
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (
    public.authorizeforclassgrader(class_id)
    OR (
      public.authorizeforclass(class_id)
      -- A group's name can be derived from a single column, so students see a
      -- group only once it holds a column they could read under gradebook_columns RLS.
      AND EXISTS (
        SELECT 1 FROM public.gradebook_columns c
         WHERE c.gradebook_column_group_id = gradebook_column_groups.id
           AND (NOT COALESCE(c.instructor_only, false) OR c.released)
      )
    )
  );

COMMENT ON COLUMN public.gradebook_columns.position_in_group IS
  'Position within gradebook_column_group_id. Replaces the former global sort_order; display order is (group.sort_order, position_in_group, id).';

CREATE OR REPLACE VIEW public.gradebook_column_legacy_groups AS
WITH cols AS (
  SELECT gc.id,
         gc.gradebook_id,
         gc.class_id,
         gc.slug,
         gc.sort_order AS so,
         public.gradebook_column_base_group_name(gc.slug) AS base
    FROM public.gradebook_columns gc
),
seq AS (
  SELECT c.*,
         ROW_NUMBER() OVER w AS rn,
         LAG(c.so)   OVER w AS prev_so,
         LAG(c.base) OVER w AS prev_base
    FROM cols c
  WINDOW w AS (PARTITION BY c.gradebook_id ORDER BY c.so ASC, c.id ASC)
),
marked AS (
  SELECT s.*,
         CASE
           WHEN s.rn = 1                             THEN 1
           WHEN s.so <> s.prev_so + 1                THEN 1
           WHEN s.base IS DISTINCT FROM s.prev_base  THEN 1
           ELSE 0
         END AS is_new_group
    FROM seq s
)
SELECT m.*,
       SUM(m.is_new_group) OVER (PARTITION BY m.gradebook_id
                                 ORDER BY m.so, m.id
                                 ROWS UNBOUNDED PRECEDING) AS group_index
  FROM marked m;

COMMENT ON VIEW public.gradebook_column_legacy_groups IS
  'Scaffolding for the 20260920120000 backfill. Dropped at the end of that migration.';

-- The backfill renumbers nearly every column and group. Both broadcasts fan out per student,
-- so they stay off until the last renumber below.
ALTER TABLE public.gradebook_columns DISABLE TRIGGER broadcast_gradebook_columns_unified;
ALTER TABLE public.gradebook_column_groups DISABLE TRIGGER broadcast_gradebook_column_groups_insert;
ALTER TABLE public.gradebook_column_groups DISABLE TRIGGER broadcast_gradebook_column_groups_update;
ALTER TABLE public.gradebook_column_groups DISABLE TRIGGER broadcast_gradebook_column_groups_delete;

INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name, slug, sort_order, is_default)
SELECT g.class_id, g.id, 'Ungrouped', 'ungrouped', 2147483647, true
  FROM public.gradebooks g
ON CONFLICT (gradebook_id, slug) DO NOTHING;

WITH ins AS (
  INSERT INTO public.gradebook_column_groups
         (class_id, gradebook_id, name, slug, sort_order, auto_assign_slug_base)
  SELECT DISTINCT ON (r.gradebook_id, r.group_index)
         r.class_id,
         r.gradebook_id,
         public.gradebook_column_group_display_name(r.base),
         r.base || '-' || r.group_index,
         (r.group_index - 1)::integer,
         r.base
    FROM public.gradebook_column_legacy_groups r
   ORDER BY r.gradebook_id, r.group_index, r.so, r.id
  RETURNING id, gradebook_id, slug
)
UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = ins.id
  FROM public.gradebook_column_legacy_groups r
  JOIN ins ON ins.gradebook_id = r.gradebook_id
          AND ins.slug = r.base || '-' || r.group_index
 WHERE gc.id = r.id;

UPDATE public.gradebook_columns gc
   SET position_in_group = sub.pos
  FROM (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY gradebook_column_group_id
                              ORDER BY sort_order, id) - 1 AS pos
      FROM public.gradebook_columns
     WHERE gradebook_column_group_id IS NOT NULL
  ) sub
 WHERE gc.id = sub.id;

DO $$
DECLARE
  v_ungrouped     integer;
  v_order_diffs   integer;
  v_split_runs    integer;
  v_merged_runs   integer;
  v_name_diffs    integer;
  v_dupe_orders   integer;
BEGIN
  SELECT count(*) INTO v_ungrouped
    FROM public.gradebook_columns
   WHERE gradebook_column_group_id IS NULL OR position_in_group IS NULL;
  IF v_ungrouped > 0 THEN
    RAISE EXCEPTION 'backfill: % columns were left without a group or a position', v_ungrouped;
  END IF;

  SELECT count(*) INTO v_order_diffs
    FROM (
      SELECT ROW_NUMBER() OVER (PARTITION BY c.gradebook_id
                                ORDER BY c.sort_order, c.id) AS old_pos,
             ROW_NUMBER() OVER (PARTITION BY c.gradebook_id
                                ORDER BY g.sort_order, c.position_in_group, c.id) AS new_pos
        FROM public.gradebook_columns c
        JOIN public.gradebook_column_groups g ON g.id = c.gradebook_column_group_id
    ) t
   WHERE t.old_pos <> t.new_pos;
  IF v_order_diffs > 0 THEN
    RAISE EXCEPTION 'backfill: % columns would render in a different position than before', v_order_diffs;
  END IF;

  SELECT count(*) INTO v_split_runs
    FROM (
      SELECT count(DISTINCT gc.gradebook_column_group_id) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       GROUP BY r.gradebook_id, r.group_index
    ) x
   WHERE x.n <> 1;

  SELECT count(*) INTO v_merged_runs
    FROM (
      SELECT count(DISTINCT (r.gradebook_id, r.group_index)) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       GROUP BY gc.gradebook_column_group_id
    ) x
   WHERE x.n <> 1;

  IF v_split_runs > 0 OR v_merged_runs > 0 THEN
    RAISE EXCEPTION 'backfill: partition mismatch (% runs split, % runs merged)',
      v_split_runs, v_merged_runs;
  END IF;

  SELECT count(*) INTO v_name_diffs
    FROM public.gradebook_column_legacy_groups r
    JOIN public.gradebook_columns gc ON gc.id = r.id
    JOIN public.gradebook_column_groups g ON g.id = gc.gradebook_column_group_id
   WHERE g.name IS DISTINCT FROM public.gradebook_column_group_display_name(r.base);
  IF v_name_diffs > 0 THEN
    RAISE EXCEPTION 'backfill: % columns sit under a differently-named header than before', v_name_diffs;
  END IF;

  SELECT count(*) INTO v_dupe_orders
    FROM (
      SELECT gradebook_id, sort_order
        FROM public.gradebook_columns
       GROUP BY gradebook_id, sort_order
      HAVING count(*) > 1
    ) d;
  IF v_dupe_orders > 0 THEN
    RAISE WARNING 'backfill: % duplicate (gradebook_id, sort_order) pairs; browser order for those was undefined, SQL tie-broke on id', v_dupe_orders;
  END IF;

  RAISE NOTICE 'backfill phase one: reproduced the legacy grouping for % columns in % groups',
    (SELECT count(*) FROM public.gradebook_columns),
    (SELECT count(*) FROM public.gradebook_column_groups WHERE NOT is_default);
END $$;

CREATE TABLE public._cg_correction_ledger (
  column_id  bigint PRIMARY KEY,
  correction text NOT NULL
);

CREATE TEMP TABLE _cg_merge_map AS
WITH fams AS (
  SELECT gradebook_id,
         auto_assign_slug_base,
         (array_agg(id ORDER BY sort_order, id))[1] AS keep_id,
         array_agg(id) AS member_group_ids
    FROM public.gradebook_column_groups
   WHERE auto_assign_slug_base IS NOT NULL AND NOT is_default
   GROUP BY gradebook_id, auto_assign_slug_base
  HAVING count(*) > 1
)
SELECT gc.id AS column_id,
       f.keep_id AS new_group_id,
       ROW_NUMBER() OVER (PARTITION BY f.keep_id ORDER BY g.sort_order, gc.position_in_group, gc.id) - 1
         AS new_position
  FROM fams f
  JOIN public.gradebook_column_groups g
    ON g.id = ANY (f.member_group_ids)
  JOIN public.gradebook_columns gc
    ON gc.gradebook_column_group_id = g.id;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT column_id, 'C1 merged a family that a deleted column had split in two'
  FROM _cg_merge_map
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = m.new_group_id,
       position_in_group         = m.new_position
  FROM _cg_merge_map m
 WHERE gc.id = m.column_id;

DELETE FROM public.gradebook_column_groups g
 WHERE NOT g.is_default
   AND NOT EXISTS (SELECT 1 FROM public.gradebook_columns c
                    WHERE c.gradebook_column_group_id = g.id);

CREATE TEMP TABLE _cg_assignment_kind AS
SELECT gc.id AS column_id,
       gc.gradebook_id,
       gc.class_id,
       CASE
         WHEN a.minutes_due_after_lab IS NOT NULL      THEN 'assignment-lab'
         WHEN a.group_config <> 'individual'           THEN 'assignment-group'
         ELSE                                               'assignment-individual'
       END AS kind
  FROM public.gradebook_columns gc
  JOIN public.assignments a ON a.gradebook_column_id = gc.id;

CREATE TEMP TABLE _cg_slug_pretenders AS
SELECT gc.id AS column_id, gc.gradebook_id, gc.class_id, gc.name
  FROM public.gradebook_columns gc
 WHERE gc.slug LIKE 'assignment-%'
   AND NOT EXISTS (SELECT 1 FROM public.assignments a WHERE a.gradebook_column_id = gc.id);

CREATE OR REPLACE FUNCTION public._cg_ensure_group(
  p_gradebook_id bigint, p_class_id bigint, p_slug text, p_name text, p_auto_base text)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_id bigint;
BEGIN
  SELECT id INTO v_id
    FROM public.gradebook_column_groups
   WHERE gradebook_id = p_gradebook_id AND slug = p_slug;
  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  INSERT INTO public.gradebook_column_groups
         (class_id, gradebook_id, name, slug, sort_order, auto_assign_slug_base)
  SELECT p_class_id, p_gradebook_id, p_name, p_slug,
         COALESCE((SELECT MAX(sort_order) + 1
                     FROM public.gradebook_column_groups
                    WHERE gradebook_id = p_gradebook_id AND NOT is_default), 0),
         p_auto_base
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;

CREATE TEMP TABLE _cg_c2a_targets AS
SELECT k.column_id,
       public._cg_ensure_group(
         k.gradebook_id, k.class_id, k.kind,
         CASE k.kind
           WHEN 'assignment-lab'   THEN 'Labs'
           WHEN 'assignment-group' THEN 'Group Assignments'
           ELSE                         'Assignments'
         END,
         k.kind) AS new_group_id
  FROM _cg_assignment_kind k;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT t.column_id, 'C2 classified from the assignments row instead of the slug'
  FROM _cg_c2a_targets t
  JOIN public.gradebook_columns gc ON gc.id = t.column_id
 WHERE gc.gradebook_column_group_id IS DISTINCT FROM t.new_group_id
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = t.new_group_id
  FROM _cg_c2a_targets t
 WHERE gc.id = t.column_id;

CREATE TEMP TABLE _cg_c2b_targets AS
SELECT p.column_id,
       public._cg_ensure_group(
         p.gradebook_id, p.class_id,
         'column-' || p.column_id::text, p.name, NULL) AS new_group_id
  FROM _cg_slug_pretenders p;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT t.column_id, 'C2 slug claimed an assignment that does not exist; moved out of the assignment group'
  FROM _cg_c2b_targets t
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = t.new_group_id
  FROM _cg_c2b_targets t
 WHERE gc.id = t.column_id;

CREATE TEMP TABLE _cg_dep_cohorts AS
WITH deps AS (
  SELECT gc.id AS column_id,
         gc.gradebook_id,
         gc.class_id,
         (SELECT array_agg(x ORDER BY x)
            FROM jsonb_array_elements_text(gc.dependencies -> 'gradebook_columns') AS t(x)
         ) AS dep_set
    FROM public.gradebook_columns gc
   WHERE gc.dependencies ? 'gradebook_columns'
     AND jsonb_array_length(gc.dependencies -> 'gradebook_columns') >= 2
)
SELECT gradebook_id, class_id, dep_set,
       array_agg(column_id ORDER BY column_id) AS column_ids
  FROM deps
 WHERE dep_set IS NOT NULL
 GROUP BY gradebook_id, class_id, dep_set
HAVING count(*) > 1;

CREATE OR REPLACE FUNCTION public._cg_common_name_prefix(p_names text[])
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  WITH b AS (
    SELECT min(n) AS lo, max(n) AS hi, array_length(p_names, 1) AS cnt
      FROM unnest(p_names) AS t(n)
  ),
  l AS (
    SELECT b.lo, b.cnt,
           (SELECT COALESCE(max(i), 0)
              FROM generate_series(1, least(length(b.lo), length(b.hi))) AS i
             WHERE left(b.lo, i) = left(b.hi, i)) AS lcp
      FROM b
  )
  SELECT CASE
           WHEN l.cnt = 1 THEN NULLIF(btrim(l.lo), '')
           WHEN l.cnt >= 2 AND l.lcp >= 3
             THEN NULLIF(btrim(regexp_replace(left(l.lo, l.lcp), '[[:space:][:punct:]]*[0-9]*[[:space:][:punct:]]*$', '')), '')
           ELSE NULL
         END
    FROM l;
$$;

CREATE TEMP TABLE _cg_c3_targets AS
WITH scattered AS (
  SELECT c.*,
         (SELECT count(DISTINCT gc.gradebook_column_group_id)
            FROM public.gradebook_columns gc
           WHERE gc.id = ANY (c.column_ids)) AS groups_now,
         (SELECT public._cg_common_name_prefix(array_agg(gc.name))
            FROM public.gradebook_columns gc
           WHERE gc.id = ANY (c.column_ids)) AS common_name,
         (SELECT CASE WHEN count(DISTINCT dep.gradebook_column_group_id) = 1
                      THEN max(dg.name) END
            FROM unnest(c.dep_set) AS d(dep_id)
            JOIN public.gradebook_columns dep
              ON dep.id = d.dep_id::bigint
            JOIN public.gradebook_column_groups dg
              ON dg.id = dep.gradebook_column_group_id) AS dep_group_name
    FROM _cg_dep_cohorts c
)
SELECT unnest(s.column_ids) AS column_id,
       public._cg_ensure_group(
         s.gradebook_id, s.class_id,
         'derived-' || md5(s.dep_set::text),
         COALESCE(NULLIF(s.dep_group_name, '') || ' Summary',
                  s.common_name,
                  'Computed'),
         NULL) AS new_group_id
  FROM scattered s
 WHERE s.groups_now > 1;

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT t.column_id, 'C3 grouped with the other columns that read the same inputs'
  FROM _cg_c3_targets t
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_columns gc
   SET gradebook_column_group_id = t.new_group_id
  FROM _cg_c3_targets t
 WHERE gc.id = t.column_id;

CREATE TEMP TABLE _cg_c4_renames AS
WITH prefixes AS (
  SELECT g.id AS group_id,
         g.gradebook_id,
         g.sort_order,
         g.name AS current_name,
         public._cg_common_name_prefix(array_agg(gc.name)) AS common_name
    FROM public.gradebook_column_groups g
    JOIN public.gradebook_columns gc ON gc.gradebook_column_group_id = g.id
   WHERE NOT g.is_default
     AND g.slug NOT IN ('assignment-lab', 'assignment-individual', 'assignment-group')
   GROUP BY g.id, g.gradebook_id, g.sort_order, g.name
),
candidates AS (
  SELECT p.*,
         lower(regexp_replace(btrim(p.common_name), 's$', '')) AS norm,
         ROW_NUMBER() OVER (
           PARTITION BY p.gradebook_id, lower(regexp_replace(btrim(p.common_name), 's$', ''))
           ORDER BY p.sort_order, p.group_id) AS claim_rank
    FROM prefixes p
   WHERE p.common_name IS NOT NULL
     AND p.common_name IS DISTINCT FROM p.current_name
)
SELECT c.group_id, c.common_name
  FROM candidates c
 WHERE c.claim_rank = 1
   AND NOT EXISTS (
     SELECT 1 FROM public.gradebook_column_groups o
      WHERE o.gradebook_id = c.gradebook_id
        AND o.id <> c.group_id
        AND lower(regexp_replace(btrim(o.name), 's$', '')) = c.norm
   );

INSERT INTO public._cg_correction_ledger (column_id, correction)
SELECT gc.id, 'C4 header renamed from the column names instead of the slug'
  FROM _cg_c4_renames r
  JOIN public.gradebook_columns gc ON gc.gradebook_column_group_id = r.group_id
ON CONFLICT (column_id) DO NOTHING;

UPDATE public.gradebook_column_groups g
   SET name = r.common_name
  FROM _cg_c4_renames r
 WHERE g.id = r.group_id;

DELETE FROM public.gradebook_column_groups g
 WHERE NOT g.is_default
   AND NOT EXISTS (SELECT 1 FROM public.gradebook_columns c
                    WHERE c.gradebook_column_group_id = g.id);

UPDATE public.gradebook_columns gc
   SET position_in_group = sub.pos
  FROM (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY gradebook_column_group_id
                              ORDER BY sort_order, id) - 1 AS pos
      FROM public.gradebook_columns
     WHERE gradebook_column_group_id IS NOT NULL
  ) sub
 WHERE gc.id = sub.id
   AND gc.position_in_group IS DISTINCT FROM sub.pos;

UPDATE public.gradebook_column_groups g
   SET sort_order = sub.pos
  FROM (
    SELECT gg.id,
           ROW_NUMBER() OVER (
             PARTITION BY gg.gradebook_id
             ORDER BY COALESCE((SELECT min(c.sort_order)
                                  FROM public.gradebook_columns c
                                 WHERE c.gradebook_column_group_id = gg.id),
                               2147483647),
                      gg.sort_order, gg.id) - 1 AS pos
      FROM public.gradebook_column_groups gg
     WHERE NOT gg.is_default
  ) sub
 WHERE g.id = sub.id
   AND g.sort_order IS DISTINCT FROM sub.pos;

ALTER TABLE public.gradebook_columns ENABLE TRIGGER broadcast_gradebook_columns_unified;
ALTER TABLE public.gradebook_column_groups ENABLE TRIGGER broadcast_gradebook_column_groups_insert;
ALTER TABLE public.gradebook_column_groups ENABLE TRIGGER broadcast_gradebook_column_groups_update;
ALTER TABLE public.gradebook_column_groups ENABLE TRIGGER broadcast_gradebook_column_groups_delete;

DO $$
DECLARE
  v_split   integer;
  v_merged  integer;
  v_touched integer;
  v_total   integer;
BEGIN
  SELECT count(*) INTO v_split
    FROM (
      SELECT count(DISTINCT gc.gradebook_column_group_id) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       WHERE NOT EXISTS (SELECT 1 FROM public._cg_correction_ledger l WHERE l.column_id = r.id)
       GROUP BY r.gradebook_id, r.group_index
    ) x
   WHERE x.n <> 1;

  SELECT count(*) INTO v_merged
    FROM (
      SELECT count(DISTINCT (r.gradebook_id, r.group_index)) AS n
        FROM public.gradebook_column_legacy_groups r
        JOIN public.gradebook_columns gc ON gc.id = r.id
       WHERE NOT EXISTS (SELECT 1 FROM public._cg_correction_ledger l WHERE l.column_id = r.id)
       GROUP BY gc.gradebook_column_group_id
    ) x
   WHERE x.n <> 1;

  IF v_split > 0 OR v_merged > 0 THEN
    RAISE EXCEPTION 'corrections: % untouched runs split and % untouched runs merged; a correction reached further than it claims',
      v_split, v_merged;
  END IF;

  SELECT count(*) INTO v_touched FROM public._cg_correction_ledger;
  SELECT count(*) INTO v_total   FROM public.gradebook_columns;
  RAISE NOTICE 'corrections: % of % columns regrouped; the rest are exactly where the heuristic had them',
    v_touched, v_total;
END $$;

DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT l.correction, count(*) AS n
      FROM public._cg_correction_ledger l
     GROUP BY l.correction
     ORDER BY count(*) DESC
  LOOP
    RAISE NOTICE 'correction applied to % column(s): %', r.n, r.correction;
  END LOOP;
END $$;

ALTER TABLE public.gradebook_columns
  ALTER COLUMN gradebook_column_group_id SET NOT NULL,
  ALTER COLUMN position_in_group SET NOT NULL;

ALTER TABLE public.gradebook_columns
  ALTER COLUMN position_in_group SET DEFAULT -1;

ALTER TABLE public.gradebook_columns
  ADD CONSTRAINT gradebook_columns_group_fk
  FOREIGN KEY (gradebook_column_group_id, gradebook_id)
  REFERENCES public.gradebook_column_groups (id, gradebook_id)
  ON DELETE RESTRICT;

ALTER TABLE public.gradebook_columns
  ADD CONSTRAINT gradebook_columns_position_key
  UNIQUE (gradebook_column_group_id, position_in_group) DEFERRABLE INITIALLY DEFERRED;

DROP VIEW IF EXISTS public.gradebook_column_legacy_groups;

DROP TRIGGER IF EXISTS gradebook_columns_enforce_sort_order_tr ON public.gradebook_columns;

ALTER TABLE public.gradebook_columns DROP COLUMN sort_order;

DROP FUNCTION IF EXISTS public._cg_ensure_group(bigint, bigint, text, text, text);
DROP FUNCTION IF EXISTS public._cg_common_name_prefix(text[]);
DROP TABLE IF EXISTS public._cg_correction_ledger;

DROP INDEX IF EXISTS public.idx_gradebook_columns_id_covering;
CREATE INDEX IF NOT EXISTS idx_gradebook_columns_group_position
  ON public.gradebook_columns (gradebook_column_group_id, position_in_group) INCLUDE (id);
CREATE INDEX IF NOT EXISTS idx_gradebook_columns_gradebook_group
  ON public.gradebook_columns (gradebook_id, gradebook_column_group_id);

-- Students are not sent a group until it holds a column they can see, so when a column
-- becomes visible (inserted, released, un-hidden or moved) its group is sent to them then.
CREATE OR REPLACE FUNCTION public.broadcast_gradebook_column_groups_on_column_visibility()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_rows jsonb;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT jsonb_agg(to_jsonb(g) ORDER BY g.class_id) INTO v_rows
      FROM public.gradebook_column_groups g
     WHERE g.id IN (SELECT n.gradebook_column_group_id FROM new_table n
                     WHERE NOT COALESCE(n.instructor_only, false) OR n.released);
  ELSE
    SELECT jsonb_agg(to_jsonb(g) ORDER BY g.class_id) INTO v_rows
      FROM public.gradebook_column_groups g
     WHERE g.id IN (
       SELECT n.gradebook_column_group_id
         FROM new_table n
         JOIN old_table o ON o.id = n.id
        WHERE (NOT COALESCE(n.instructor_only, false) OR n.released)
          AND (o.gradebook_column_group_id IS DISTINCT FROM n.gradebook_column_group_id
               OR NOT (NOT COALESCE(o.instructor_only, false) OR o.released)));
  END IF;

  IF v_rows IS NOT NULL THEN
    PERFORM public._broadcast_gradebook_column_group_rows('UPDATE', v_rows, true);
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS gradebook_columns_broadcast_group_visibility_insert ON public.gradebook_columns;
CREATE TRIGGER gradebook_columns_broadcast_group_visibility_insert
  AFTER INSERT ON public.gradebook_columns
  REFERENCING NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.broadcast_gradebook_column_groups_on_column_visibility();

DROP TRIGGER IF EXISTS gradebook_columns_broadcast_group_visibility_update ON public.gradebook_columns;
CREATE TRIGGER gradebook_columns_broadcast_group_visibility_update
  AFTER UPDATE ON public.gradebook_columns
  REFERENCING OLD TABLE AS old_table NEW TABLE AS new_table
  FOR EACH STATEMENT EXECUTE FUNCTION public.broadcast_gradebook_column_groups_on_column_visibility();
